spring: 
  profiles: 
    active: 
      - dev
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false

server:
  port: 8080
  contextPath: /api/
  compression: 
    enable: true
    mime-types: application/json